components:
- name: InMemoryDocumentStore
  params:
    use_bm25: true
  type: InMemoryDocumentStore
- name: Retriever
  params:
    document_store: InMemoryDocumentStore
    top_k: 30
  type: BM25Retriever
- name: Reranker
  params:
    batch_size: 32
    model_name_or_path: cross-encoder/ms-marco-MiniLM-L-6-v2
    top_k: 1
    use_gpu: false
  type: SentenceTransformersRanker
- name: PromptModel
  params:
    model_kwargs:
        model_kwargs:
            #device_map: {"": 0}
            torch_dtype: "auto"
            do_sample: false
        generation_kwargs:
            max_length: 10
    model_name_or_path: "Intel/fid_flan_t5_base_nq"
    invocation_layer_class: fastrag.prompters.invocation_layers.fid.FiDHFLocalInvocationLayer
    use_gpu: false
  type: PromptModel
- name: AnswerParser
  params: {}
  type: AnswerParser
- name: lfqa
  params:
    output_parser: AnswerParser
    prompt: "{query}"
  type: PromptTemplate
- name: Reader
  params:
    default_prompt_template: lfqa
    model_name_or_path: PromptModel
  type: PromptNode
pipelines:
- name: my_pipeline
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Reranker
  - inputs:
    - Reranker
    name: Reader
version: 1.23.0
